// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: vote/rpc/pb/vote.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Vote_SendVote_FullMethodName         = "/pb.Vote/SendVote"
	Vote_ChangeStateSlave_FullMethodName = "/pb.Vote/ChangeStateSlave"
)

// VoteClient is the client API for Vote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoteClient interface {
	SendVote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteRes, error)
	ChangeStateSlave(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteRes, error)
}

type voteClient struct {
	cc grpc.ClientConnInterface
}

func NewVoteClient(cc grpc.ClientConnInterface) VoteClient {
	return &voteClient{cc}
}

func (c *voteClient) SendVote(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteRes)
	err := c.cc.Invoke(ctx, Vote_SendVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voteClient) ChangeStateSlave(ctx context.Context, in *VoteReq, opts ...grpc.CallOption) (*VoteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteRes)
	err := c.cc.Invoke(ctx, Vote_ChangeStateSlave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoteServer is the server API for Vote service.
// All implementations must embed UnimplementedVoteServer
// for forward compatibility.
type VoteServer interface {
	SendVote(context.Context, *VoteReq) (*VoteRes, error)
	ChangeStateSlave(context.Context, *VoteReq) (*VoteRes, error)
	mustEmbedUnimplementedVoteServer()
}

// UnimplementedVoteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoteServer struct{}

func (UnimplementedVoteServer) SendVote(context.Context, *VoteReq) (*VoteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVote not implemented")
}
func (UnimplementedVoteServer) ChangeStateSlave(context.Context, *VoteReq) (*VoteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeStateSlave not implemented")
}
func (UnimplementedVoteServer) mustEmbedUnimplementedVoteServer() {}
func (UnimplementedVoteServer) testEmbeddedByValue()              {}

// UnsafeVoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoteServer will
// result in compilation errors.
type UnsafeVoteServer interface {
	mustEmbedUnimplementedVoteServer()
}

func RegisterVoteServer(s grpc.ServiceRegistrar, srv VoteServer) {
	// If the following call pancis, it indicates UnimplementedVoteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Vote_ServiceDesc, srv)
}

func _Vote_SendVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServer).SendVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vote_SendVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServer).SendVote(ctx, req.(*VoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vote_ChangeStateSlave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServer).ChangeStateSlave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vote_ChangeStateSlave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServer).ChangeStateSlave(ctx, req.(*VoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Vote_ServiceDesc is the grpc.ServiceDesc for Vote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Vote",
	HandlerType: (*VoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendVote",
			Handler:    _Vote_SendVote_Handler,
		},
		{
			MethodName: "ChangeStateSlave",
			Handler:    _Vote_ChangeStateSlave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vote/rpc/pb/vote.proto",
}
