[info]
type = "master"
term = 0
name = "serve0"

[heartbeat]
port = 8889
    [[serve]]
    name = "serve1"
    ip = "127.0.0.1:8890"

    [[serve]]
    name = "serve2"
    ip = "127.0.0.1:8891"

[vote]
port = 8789
    [[serve]]
    name = "serve1"
    ip = "127.0.0.1:8790"

    [[serve]]
    name = "serve2"
    ip = "127.0.0.1:8791"
